### PR TITLE
Use prettier option 'semi' for jsx semi colons

### LINKED ISSUE #169: 🐛 BUG: Inconsistent formatting between frontmatter and component code
### Describe the Bug

Using `v0.1.0-next.4` I get this formatted code:

```astro
---
import ConfigOption from "./ConfigOption.astro";
const DEFAULT_LOCALE = "en";

const [options] = Astro.fetchContent<FetchContentResultBase>(
  "../../nebula-docs/src/data/config-reference.md"
);

const { locale = DEFAULT_LOCALE } = Astro.props;

// Default locale options, for use as fallback if localization is not available
const fallbackOptions = options[DEFAULT_LOCALE].options;
// config options for locale
const configOptions = options[locale] ? options[locale].options : fallbackOptions;
---

<style lang="scss">
  .config-block {
    margin-bottom: 1.5rem;
  }
</style>

{configOptions.map((option, optionIndex) => {
  const fallbackOption = fallbackOptions[optionIndex]

  return (
    <div class="config-block">
      <ConfigOption
        isRequired={option.required}
        description={option.description ?? fallbackOption.description}
        example={option.example ?? fallbackOption.example}
      >
        <h2 id={option.name}>
          {option.name}
          <a
            aria-hidden="true"
            tabindex={-1}
            class="heading-link no-underline"
            href={`#${option.name}`}
          >
            <span class="fas fa-link" />
          </a>
        </h2>
      </ConfigOption>
      {option.suboptions &&
        option.suboptions.map((suboption, subIndex) => {
          const fallbackSuboption = fallbackOption.suboptions[subIndex]

          return (
            <ConfigOption
              isRequired={suboption.required}
              description={suboption.description ?? fallbackSuboption.description}
              example={suboption.example ?? fallbackSuboption.example}
            >
              <h3 id={`${option.name}-${suboption.name}`.replace(new RegExp(", ", "g"), "-")}>
                {option.name}.{suboption.name}
                <a
                  aria-hidden="true"
                  tabindex={-1}
                  class="heading-link no-underline"
                  href={`#${option.name}-${suboption.name}`.replace(new RegExp(", ", "g"), "-")}
                >
                  <span class="fas fa-link" />
                </a>
              </h3>
            </ConfigOption>
          )
        })}
    </div>
  )
})}
```

The important part is that `const fallbackOption = fallbackOptions[optionIndex]` gets formatted sans semicolon for some reason? Presumably b/c of different config defaults or a different parser/printer?

It seems like lines of code in a block in the body like the `map(() => {})` will be formatted w/o semicolon v.s. the frontmatter will have semicolons by default

### Steps to Reproduce

Format the above file; see that nothing changes

### PR DESCRIPTION
**Pull request by antonyfaris**
## Changes

- Fixes #169

## Testing

- Change a couple of tests.

## Docs

### CODE REVIEW

File: src/printer.ts [hunk 1]
```diff
@@ -523,7 +523,7 @@ function embed(
 		content = textToDoc(forceIntoExpression(textContent), {
 			...opts,
 			parser: expressionParser,
-			semi: false,
+			semi: opts.semi,
```
Comment (Princesseuh) [inline src/printer.ts:526]: Would it make sense to also change line 549 (attributes using expressions) with this change? 

(also, presumably these lines can be omitted completely due to the spread on top)

Comment (antonyfaris) [reply src/printer.ts]: Done!
