### PR TITLE
Format markdown component content

### LINKED ISSUE #41: 🐛 BUG: Markdown component indentation broken
### Describe the Bug

Astro prettier plugin breaks markdown inside `Markdown` component when it's nested in another element

### Steps to Reproduce

* Install astro prettier plugin
* Open attached file
* Format document

* Expected: indentation preserved
* Seen: Second paragraph indented (which then results in `<pre>` markup)

[test.astro.zip](https://github.com/snowpackjs/prettier-plugin-astro/files/7385211/test.astro.zip)

Before format document:

```
---
---



<div>
  <Markdown>
    Test Test

    Test
  </Markdown>
</div>
```

After format document: 

```
---
---



<div>
  <Markdown>
    Test Test

        Test
  </Markdown>
</div>
```

### LINKED ISSUE #42: 🐛 BUG: Components inside `<Markdown>` are deleted by formatting the document
### Describe the Bug

Components inside `<Markdown>` are deleted by formatting the document

### Describe the Bug

Astro prettier plugin deletes components inside a `Markdown` component

### Steps to Reproduce

* Install astro prettier plugin
* Copy-and-paste below input into a new `.astro` file
* Format document

* Expected: Inner component remains
* Seen: Inner component deleted

Input document:

```
---
---



<div>
  <Markdown>
  <Fragment>test</Fragment>
  </Markdown>
</div>
```

After format document: 

```
---
---



<div>
  <Markdown></Markdown>
</div>
```

### PR DESCRIPTION
**Pull request by antonyfaris**
## Changes

Fixes the format of markdown inside a markdown component.
Fixes #41
Fixes #42

## Testing

I added an extra test.

## Docs

### CODE REVIEW

File: src/printer.ts [hunk 1]
```diff
@@ -559,9 +495,8 @@ function embed(path: AstPath, print: printFn, textToDoc: (text: string, options:
         // the css parser appends an extra indented hardline, which we want outside of the `indent()`,
         // so we remove the last element of the array
         let formattedStyles = textToDoc(styleTagContent, { ...opts, parser: parserLang });
-        if (typeof formattedStyles === 'string') return formattedStyles;
-        if (isDocCommand(formattedStyles)) return formattedStyles;
-        formattedStyles = formattedStyles[0];
+
+        formattedStyles = stripTrailingHardline(formattedStyles);
```
Comment (jasikpark) [inline src/printer.ts:499]: Oh! I appreciate the function instead of the other logic

**Review by jasikpark — APPROVED** [review]
Looks good to me!

**Comment by jasikpark** [comment]
Thanks for your patience with my review of it - sorry for letting it sit for a bit
